version: "3.9"
services:
  web:
    build: .
    image: openlhc-anomaly:latest
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./:/app:cached
      - ./data:/app/data
      - ./results:/app/results
    command: ["streamlit", "run", "webapp/app.py"]
